name: Crewl CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2
          
        - name: Run Lint
          run: ./gradlew lintDebug

        - name: Upload HTML test report
          uses: action/upload-artifact@v2
          with:
            name: index.html
            path: app/build/reports/lint-results-debug.html
